### ISSUE TITLE
Distance as a function of degree (Fig2). 

### ISSUE THREAD

**Issue by AurinaBMH** [AurinaBMH/WORMPlosCBtemplate#10]
If I understand it right, the distance in this plot (yellow) is normalized. 

dMeanNorm = 1+0.8*(dMean(:,1)-dMean(1,1))/(max(dMean(:,1))-dMean(1,1));
in  PlotRichClub.m function

Is there a reason to present normalized distance between neurons when we can just show original?
It is also not mentioned in the text. While reading it seems a little weird that the worm is 1mm long, but average distances between neurons go up to 1.8. 

I would vote for showing original distances between neurons.

**Comment by benfulcher** [comment]
Yes it's a todo in the caption. This is just to have it fit in the same scale as phi so they look nicely on the plot. Eventually will add a scale to the right of the plot for distances (mm)
