### ISSUE TITLE
Unclear lineage sentence

### ISSUE THREAD

**Issue by benfulcher** [AurinaBMH/WORMPlosCBtemplate#101]
> In the mammalian brain, neuronal lineage has been associated with both functional \cite{Ciceri2013, Li2012} and connectivity-related properties \cite{Yu2012}.

What do you mean by function and connectivity-related? Would it make sense to say:
"functional \cite{} and structural \cite{} connectivity-related properties"?? Many readers will think of functional connectivity when talking about `connectivity-related properties`...

**Comment by AurinaBMH** [comment]
functional here is not related to functional connectivity - it's about the function that specific groups of neurons are performing. It's about 'functional properties' and connectivity-related properties. 
E.g. Clonally related visual cortical neurons show similar stimulus feature selectivity (title of the Li2012).

**Comment by benfulcher** [comment]
Hence the confusion; can you clarify the text?

**Comment by AurinaBMH** [comment]
will try :)

**Comment by AurinaBMH** [comment]
In the mammalian brain, neuronal lineage has been associated with both functional \cite{Ciceri2013, Li2012} properties as well as connectivity \cite{Yu2012}.

better?
