### ISSUE TITLE
valid genes in this analysis?

### ISSUE THREAD

**Issue by benfulcher** [AurinaBMH/WORMPlosCBtemplate#102]
> Thus, although a direct test of the metabolic hypothesis for neural hubs is not possible from current data, we investigated whether other biological process GO categories were overrepresented in pairs of connected hubs using ORA (for 30 out of 168 valid genes for this analysis), with results listed in Table~\ref{tab:enrichmentRICH}.

@AurinaBMH can you clarify what "for 30 out of 168 valid genes for this analysis" refers to? It kind of comes out of nowhere. Could either delete or clarify...?

**Comment by AurinaBMH** [comment]
Changed to 'of 30 genes relative to the 168 genes with sufficient data for this analysis' as before fro connected/unconnected. Does that help?
