### ISSUE TITLE
Matching interneurons

### ISSUE THREAD

**Issue by AurinaBMH** [AurinaBMH/WORMPlosCBtemplate#105]
AF: "I keep commenting on this. need to specify what you mean by projection pattern. - same mean distance? same targets?"

We first used 'source' and 'target', then 'origin and termination' locations and then I asked Roger, he suggested using ‘position' and 'projection pattern’ instead of origin and termination.

What do you mean by same distance? - these neurons would have approx similar body position, would terminate in the same area as hubs and would have same axon length. 
How would you recommend to phrase this?

**Comment by alexfornito** [comment]
You just need to indicate exatcly how you matched the neurons. On what properties? Determined how? As per your explanation below.

**Comment by benfulcher** [comment]
We emailed Roger who recommended this terminology. @alexfornito, if you want to reword, can discuss with Roger???
> their position and projection pattern

**Comment by alexfornito** [comment]
I know but if I am trying to reproduce I will have no idea how to. What specific criteria were chosen? E.g.,

 

³Because these neurons project to similar targets²

 

or have ³same mean connection distance². Or ³all have projections that extend from head to tail²?

**Comment by AurinaBMH** [comment]
Is this better? 

Specifically, we selected a subset of nonhub interneurons that most closely resemble the anatomical properties of hub interneurons, in terms of their position and projection pattern: AVFL, AVFR, AVHL, AVHR, AVKR, AVJL, and AVJR, meaning that their bodies are in similar locations in the head and axons project to similar targets in the tail.

**Comment by alexfornito** [comment]
Nice. slight reword:

 

Specifically, we selected a subset of nonhub interneurons that most closely resemble the anatomical properties of hub interneurons in terms of their position and projection pattern; that is, the cells are in similar locations in the head and their axons project to similar targets in the tail. These neurons were AVFL, AVFR, AVHL, AVHR, AVKR, AVJL, and AVJR.

**Comment by AurinaBMH** [comment]
fixed
