### ISSUE TITLE
FIG S1

### ISSUE THREAD

**Issue by AurinaBMH** [AurinaBMH/WORMPlosCBtemplate#107]
AF: bit confusing to use blue to indicate positive values in panels C and D.
Better to just used red scale?

AA: this would involve a lot of manual changes - don't think it's worth investing time for a supp figure. Ben?

**Comment by AurinaBMH** [comment]
![image](https://user-images.githubusercontent.com/14971156/31476932-cdcb7860-af54-11e7-8f6d-fa30317486a8.png)
That's a test run for the average of 100 matrices (Pearson). 
The ones that have a trend, might look fine, but pearson and coX will look bad - we need the middle to be white in order to see the scattering of values. 
I am inclined not to make changes to S1.

**Comment by benfulcher** [comment]
Let's keep as it is; color bars are clearly labeled and just a suppl figure. Unless you feel strongly, @alexfornito ??
