### ISSUE TITLE
Discussion paragraph...?

### ISSUE THREAD

**Issue by benfulcher** [AurinaBMH/WORMPlosCBtemplate#109]
Difficult to say (i) that CGE decreases with distance (since effect is specific and small) but helps tie into the "despite long spatial seapration of hub pairs"... @alexfornito what do you think of this?:
> Specifically, we show that:
> (i) CGE is higher for connected pairs of neurons compared to unconnnected pairs;
> (ii) the neuron connection probability decays as a function of spatial separation, and;
> (iii) connected pairs of hub neurons, which are generally separated by longer anatomical distances, show the highest levels of CGE.

**Comment by alexfornito** [comment]
Looks good
