### ISSUE TITLE
Modules: test to compare distributions

### ISSUE THREAD

**Issue by AurinaBMH** [AurinaBMH/WORMPlosCBtemplate#11]
When we comparing any distributions (except curves for rich, feeder, peripheral links) we use ranksum test (distributions are not normal)

In the modules sections when comparing (inter/intra; as well as hubs within modules to other within modules links) you used ttest. Fig 5B and C. 
Is there a reason for that? otherwise, I think we should use ranksum through the manuscript because all distributions are not normal.

**Comment by benfulcher** [comment]
Ok, I'll try to change to ranksum for consistency. Welch's t-test is typically fairly robust to distributions where mean and std make sense, but you're right that these guys have large outliers that would skew means and stds. Will change to ranksum
