### ISSUE TITLE
Assigning coordinates

### ISSUE THREAD

**Issue by benfulcher** [AurinaBMH/WORMPlosCBtemplate#12]
Aurina,

> Coordinates for three neurons (AIBL, AIYL, SMDVL) were missing in this dataset, and were reconstructed based on the positions of the contralateral neurons (AIBR, AIYR, SMDVR) by assigning identical coordinates for the contralateral neurons in these three pairs according to Varier and Kaiser \cite{Varier2011}.

You mention this is done by Varier but they don't motivate why. I can't find that they've done this in Varier at all? They describe how they infer a 3-dimensional co-ordinate, but I can't find any reference to assigning coordinates for missing neurons...? Am I missing something here?

**Comment by AurinaBMH** [comment]
Here is the part from methods where they say, reconstruction was done based on the data from corresponding bilateral counterparts. 

Three-dimensional coordinates were based on the two-dimensional spatial information of C. elegans neurons [36] <http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1001044#pcbi.1001044-Choe1>, which were updated with spatial information of three neurons that had been excluded. The data for neurons that did not have associated spatial information were obtained based on the spatial data of corresponding bilateral counterparts.

**Comment by benfulcher** [comment]
Ah yes, I missed this -- thanks. So we definitely need to cite the original Choe article

**Comment by benfulcher** [comment]
I guess the difference is that in the Verier paper, they use 3d co-ordinates, so no neurons have zero distance -- they'll just be very close but on the other hemisphere. Perhaps I should work up a 3-d coordinate approach -- if I were a reviewer I'd ask

**Comment by benfulcher** [comment]
I've messaged Choe directly about the paper and the data source -- I cannot track down his article, or how the coordinates were obtained anywhere

**Comment by benfulcher** [comment]
He's responded; I will cite him
