### ISSUE TITLE
Checking robustness to different connectome representations

### ISSUE THREAD

**Issue by benfulcher** [AurinaBMH/WORMPlosCBtemplate#13]
We should have a statement that our main results hold when gap junctions are included (or at least check quickly if this is true).

**Comment by benfulcher** [comment]
Also, from Alex, robustness to weighted results (incorporate weighted rich club results into main text), but also verify other results hold with weights

**Comment by AurinaBMH** [comment]
When we include gap junctions + synapses, the main results holds up (using Pearson correlation). 
Coexpression is highest for rich links, following by feed-out. No increase for feed-in and peripheral links. 
![image](https://user-images.githubusercontent.com/14971156/27315456-05f02d4a-55bd-11e7-85a3-c541d000b584.png)

**Comment by benfulcher** [comment]
We need to say that we use both throughout for consistency with prior work, but that similar results from just the synaptic network

**Comment by AurinaBMH** [comment]
Ok, will use chemical+electrical in the main text and only chemical in the supp.

**Comment by benfulcher** [comment]
Maybe not necessary to do chemical-only analysis; perhaps just a note somewhere that similar results were obtained when analyzing the direct synaptic connectome in isolation
