### ISSUE TITLE
Multifunctional neurons in the interneuron/sensory/motor analysis

### ISSUE THREAD

**Issue by benfulcher** [AurinaBMH/WORMPlosCBtemplate#15]
Aurina, I assume we exclude multifunctional neurons from this analysis? Or are multifunctional neurons counted in multiple categories?
<img width="472" alt="screen shot 2017-05-13 at 20 57 55" src="https://cloud.githubusercontent.com/assets/4446070/26024881/dc606cf8-381e-11e7-9b0e-fabd9e896379.png">

**Comment by AurinaBMH** [comment]
In this analysis multimodal neurons are not excluded. 
If a neuron was labeled interneuron and motor neuron, it will be included on both calculations, therefore in both curves.

I don’t think that we need to exclude multimodal neurons from this plot, because it’s not like they are a separate category, they just perform functions attributed to both of these categories. Including them in both, I think, is optimal as they belong to both categories semi-equally. 

There are 23 multimodal neurons and 17 of them are labeled interneuron (and something else), so these categories are overlapping a lot. 

We could include them as a separate line in the plot (see evernote: Including multimodal neurons into types plot <https://www.evernote.com/shard/s94/nl/2147483647/e5462944-7574-47f7-b9b6-597f382e0c8b/>), but not sure if it’s informative. 
Maybe just mention in the text that categories are not mutually exclusive.

**Comment by benfulcher** [comment]
Yep I agree. Thanks for looking into this. Alex was also confused -- I've rewritten to stress that multimodal are just neurons assigned to multiple categories.
My numbers don't agree with yours, though... Am I doing something wrong:

```
    isInter = C.RegionM(:,strcmp(C.neuronAnatomyNames,'interneuron'));
    isSensory = C.RegionM(:,strcmp(C.neuronAnatomyNames,'sensory neuron'));
    isMotor = C.RegionM(:,strcmp(C.neuronAnatomyNames,'motor neuron'));
    >> sum(isInter&isSensory)
     5
    >> sum(isInter&isMotor)
     7
   >> sum(isMotor&isSensory)
     6
```

This implies 18 multimodal, of which 5 are interneurons...?

**Comment by AurinaBMH** [comment]
My bad about the numbers. 
Before in the Print_neuroconnect script neurons were labeled as multimodal if they belong to more then one (out of all 20) hierarchical category and not just interneuron/sensory/motor. 

Fixed this in the script (will push it from home in the evening - library internet access is to slow to push stuff - will let you know when it’s pushed). 
Please regenerate your C structure then to have the correct version.

**Comment by benfulcher** [comment]
Oh ok -- yeah I never used those classifications (where are they stored?)
I always used code like that above (e.g., look at `GiveMeMask`) in general I'm trying to put all code like this that might be repeated for multiple analyses in a single place -- e.g., when getting interneurons, or labeling masks, etc.
It's really hard, especially now when we're changing parts of analysis, to make sure things change everywhere -- but much easier to do this in one place in a function that multiple pieces of code use.

**Comment by AurinaBMH** [comment]
This assignment is done once when running Print_neuroconnect (it calls a function that does the assignment using hierarchy file). 
So when C structure is created assignment to sensory/interneuron/motor neuron/multimodal will not change. 

New version of the script is not pushed yet - library internet can’t handle it (weird, no?). 
I will let you know when it’s pushed, don’t forget to regenerate C structure afterwards.

**Comment by benfulcher** [comment]
Ok -- but where in C is the assignment? If I always use code like: `C.RegionM(:,strcmp(C.neuronAnatomyNames,'interneuron'))`, this should all be correct, right?
Libraries often block some ports -- ssh is a common one for shared wifi networks to block (for security purposes!) and git pushes go through ssh. I think if you changed the push to use https you'd be all good, but don't worry -- just commit locally and push when you get a more open internet connection.

**Comment by AurinaBMH** [comment]
I’m not sure what you’re asking :)

Categories are assigned to C.RegionM
rows are neurons, columns (21) are categories. 
21st column is multimodal - created after all other are assigned using hierarchy. 

No mask is done in C - just a vector for each hierarchical category and last column for multimodal neurons. 
Or did you ask something else?

If you use C.RegionM(:,strcmp(C.neuronAnatomyNames,'interneuron’)) it should be correct. 
I used multimodal column (C.RegionM(:,21)), and the mistake was there.

**Comment by benfulcher** [comment]
Ok yeah using column 21 is what I was asking. I never used that. Cool
