### ISSUE TITLE
How did we determine "similar anatomical properties"?

### ISSUE THREAD

**Issue by benfulcher** [AurinaBMH/WORMPlosCBtemplate#16]
"all pairs of nonhub interneurons with similar anatomical properties to hub interneurons (AVFL, AVFR, AVHL, AVHR, AVKL, AVKR, AVJL, AVJR, n=8)"
"ensure that increase in coexpression for rich links is not determined by the fact that the majority of hub neurons belong to the same anatomical neuron type"
"even amongst interneurons sharing same anatomical properties hub interneurons exhibit significantly increased coexpression."
It's quite vague to just say 'similar anatomical properties' -- can we be more specific? We need to say how we determined that list of 8 neurons with "similar anatomical properties"

**Comment by AurinaBMH** [comment]
These neurons were recommended by Roger to compare with hub neurons. 

In general, they start in the same place and end in general in the same regions as our hub neurons, therefore “anatomical similarity”. 
Also, they are from the same family (AV…), therefore we would confirm that just being from the same family will not give increased coexpression.

We should probably ask Roger to comment in that in more detail.

**Comment by benfulcher** [comment]
Oh whoops, there was already an issue for this. I'll leave you to go through and incorporate this info into the text, and then you can close the issue?

**Comment by benfulcher** [comment]
(in general if there's a query you can clear up -- can just describe how you fixed it here, and then close the issue if it's all resolved, esp if it's an issue assigned only to you)

**Comment by AurinaBMH** [comment]
commented in the other issue. 
Will need more information from Roger.
