### ISSUE TITLE
neurotransmitter categories represented in our analysis

### ISSUE THREAD

**Issue by benfulcher** [AurinaBMH/WORMPlosCBtemplate#18]
Can we look further into this? Where is the code? It's quite unclear at the moment.
We want to know: (i) which categories exist, (ii) which categories have genes in our dataset, (iii) which categories have enough genes to meet our 5 gene minimum.

> This may be due to the fact that only a single acetylcholine-related GO category (GO:0007271: `synaptic transmission, cholinergic') was represented in the current gene expression data (CONTAINING HOW MANY GENES?), and no glutamate release categories were represented [[]].

**Comment by AurinaBMH** [comment]
Code for looking into GO categories that exist is this:
searchGOcategories

You can choose to check for GO categories enriched in mouse (main text) or for category containing any string (eg. ‘cholinergic’, ‘glutamate’ or something else) and it will look for GO categories with this string in each of our subsets (948, 577 and 390 genes, only 577band 390 subsets are used in enrichment analysis). 

It will give how many GO categories are with these strings in them and will show how many (and what exactly) genes are in those categories for each of the above mentioned gene sets. 

E.g. `synaptic transmission, cholinergic’ is the only category with choline in it which has more then 5 genes (others have 3 or less genes in them). 
25, 20, 12 genes in each gene set respectively for 948, 577 and 390 gene sets.

**Comment by AurinaBMH** [comment]
Depending on what categories we want to check **searchGOcategories** script can be used. 
At this point in the text only mouse categories are mentioned, so I included the number of genes there (one gene, so we can't check the main hypothesis from mouse about metabolism).
