### ISSUE TITLE
Look at definition of gene score

### ISSUE THREAD

**Issue by benfulcher** [AurinaBMH/WORMPlosCBtemplate#24]
Need to really get the story straight around:

- [x] What the score is (and really justifying why we focus only on positive matches)
- [ ] How we formulate, and whether we need the negative log transform, etc.

**Comment by benfulcher** [comment]
@AurinaBMH Can you let me know when you're done checking the code and we can think about some of the subtleties, including the negative log transform, etc...?

**Comment by AurinaBMH** [comment]
Sure, I’ll do that later in the evening, was occupied with SOBR stuff for a while. 
Will let you know when it’s done. 

ermineJ can take -log of scores, bus of course we can do that prior.

**Comment by AurinaBMH** [comment]
I think gene scoring is done now. 
Excluding LR pairs from the mask changes results a bit, especially for chemical and electrical synapses (without LR pairs, a lot of categories survive FDR correction…) while if LR pairs are included, nothing survives the correction. 

Would be good to chat in person.
