### ISSUE TITLE
Enrichment on synapses versus gap junctions

### ISSUE THREAD

**Issue by benfulcher** [AurinaBMH/WORMPlosCBtemplate#28]
Can we actually distinguish synaptic connections from gap junctions?
Do they differ in coexpression? Are the enriched in different types of genes?
This should be a simple analysis to do, but would add alot to the paper.
If they're not so different, then it undermines our justification for removing gap junctions from our connectome.

**Comment by AurinaBMH** [comment]
Chemical vs electrical synapses differ in coexpression: electrical synapses have much higher coexpression (see evernote: Comparing chemical and electrical synapses <https://www.evernote.com/shard/s94/nl/2147483647/8f2c5547-04ba-4d7b-bd36-174356240a96/>)
Also, there are some enrichment differences: chemical synapses have some GO categories overrepresented (biosynthesis and metabolism related) while electrical synapses do not show anything specific about them (for corrected p values). Also see same evernote. 

Scripts used for this comparison are not pushed yet (will push from home). 

Will look deeper into this when I’m back and will incorporate this comparison into the manuscript (probably as a supp???)

**Comment by benfulcher** [comment]
Ok, thanks. Yeah, I mean we are the odd ones out in not including gap junctions in our connectome. If we get similar results for everything when including gap junctions, then our justification for excluding them (because they are genetically different) is void.
Cool result that gap junctions are more genetically similar than synaptic connections (not surprising I guess because gap junctions are probably quite stereotypical, whereas synaptic connections could be more variable??).
Cool that we could have distributions for connections by 'gap', 'synaptic', also by 'reciprocal synaptic', 'unidirecitonal synaptic', etc.

**Comment by AurinaBMH** [comment]
Did gene scoring for exclusively chemical synapses vs exclusively electrical synapses. 
No Go categories are surviving FDR, but enrichment top 15 for chemical seems to be sensible - biosynthesis and metabolism-related categories. 
Table added in the manuscript, some text as well.
