### ISSUE TITLE
Hub interneuron analysis

### ISSUE THREAD

**Issue by benfulcher** [AurinaBMH/WORMPlosCBtemplate#29]
@AurinaBMH — Can you go over the hub interneuron analysis? I didn't understand what you’ve done in terms of picking nonhub neurons with ’similar anatomical properties’ (you’ll need to explain how you selected these neurons; I labeled the paragraph [[make less vague]]. Alex struggled to follow this paragraph also. Can you address his comments through this paragraph?? Alex has suggested new wording, also.

**Comment by AurinaBMH** [comment]
These neurons (non hub interneurons) were suggested by Roger to see if other interneurons of the same class (all of them belong to the same class) and similar anatomy (start in the same area and have quite the same targets as our hub interneurons) have high coexpression as do hub interneurons.

Why exactly he suggested these neurons probably would be good to ask him - maybe he will be able provide more details. 
In my opinion it’s just a group of interneurons that are similar to our hub interneurons in terms of anatomy - similar starting and ending points and they also belong to one group (as do the majority of hub interneurons).  

Will go through this in more detail when I’m back. 
Also would be good to meet with Roger when I’m back to discuss some points about anatomy.

**Comment by benfulcher** [comment]
Great -- if you can add this detail to the manuscript as best as you can, we can ask Roger to clarify later. At the moment it's super vague what 'similar anatomical properties' are

**Comment by AurinaBMH** [comment]
Made some changes in the text. For more insights will need Roger to comment.
