### ISSUE TITLE
Enrichment hubs

### ISSUE THREAD

**Issue by benfulcher** [AurinaBMH/WORMPlosCBtemplate#3]
In the main text, we say that we get rich + feeder versus peripheral.

- [x] We need to give some justification for grouping rich + feedin + feedout for this analysis, or say that similar results were found when just rich versus non-rich was done. Could be something like for statistical power. 
AA - results for Rich vs non-rich and RichFeeder vs others are qualitatively the same. However, for rich vs non-rich analysis we get 27 genes (78/1961 links) with >0 matches and high scores, while for RichFeeder vs others there are 47 genes (641/1961 links). 
Probably can say that results are the same (and maybe show another table in the supp), but keep talks about Rich-feeder case in the text more. 

- [x] We also need to add how many links were of each type through this section (e.g., was connected versus unconnected done by symmetrizing, and in the upper triangle, then how many pairs were connected, unconnected?) What about the rich analysis -- was that also done with an upper triangle, or in a directed way? How many examples of each type was there?
AA - all gene scoring is done using symmetrized matrix (using only upper triangle). 
Nconnected = 1961
Nunconnected = 36820
Nrich = 78
Nrich&feeder = 641
N(non-rich) = 1883
N(non-rich/feeder) = 1320

- [x] To link to the node-level results, we also need to compare when feed-in and feed-out are included/excluded, since we go on to make a statement about glutamate being due to feed-in connections...?
AA: we get glutamate receptor GO categories for rich links (receive glutamate fro sensory neurons), however, there is no enrichment for glutamate itself (like sending glutamate) neither in rich&feeder enrichment (not feedIN separately). 
I did enrichment separately for only feedIN and only for feedOUT cases. 
In general, there are 190 feed in links and 404 feedOUT links. No enrichment categories are in feedIN only case. For feedOUTwe get generic BP and CC (but no MF categories). 
Glutamate receptor GO is coming from rich links (not from any type of feeders), so separating them should not change anything. 
(see FeedIN_FeedOUT.project)

- [x] Need to check whether other neurotransmitter systems are represented. Could be worth looking into which GO categories have genes annotated to them from our ~900 -- could be small enough to inspect manually (BPs).

- [x] From the tables, it looks like biological processes is probably enough to present. Let's chat about whether we also need CCs, and MPs. We only really talk about BPs -- they're part of the main story...
AA: BPs show only glutatame, basic connectivity-communication related categories come from MF, so I think it's reasonable to show all. 
Or as we talked today, run only BP and present TOP15.

**Comment by benfulcher** [comment]
I think we also need to compare when feed-in and feed-out are included/excluded, since we go on to make a statement about glutamate being due to feed-in connections...?

**Comment by AurinaBMH** [comment]
see neurotransmitter categories represented in our analysis #18 for neurotransmitter GO categories. 
Present TOP 15 GO for biological processes.
