### ISSUE TITLE
Lineage analysis

### ISSUE THREAD

**Issue by benfulcher** [AurinaBMH/WORMPlosCBtemplate#30]
Alex has left a bunch of comments -- please follow these up in text
(including a comment on the suppl figure -- alex suggests an aside of I reckon a couple sentences just describing that peripheral are most similar in lineage and interesting, feeder the most different, implying that nonhub-hub connected pairs have significantly increased lineage distance.

**Comment by AurinaBMH** [comment]
Included some references and a little more explanation why it can influence gene expression.
