### ISSUE TITLE
Median or mean for distributions

### ISSUE THREAD

**Issue by benfulcher** [AurinaBMH/WORMPlosCBtemplate#31]
Alex was keen to use median consistently, but I was worried about how representative this was (some rich club curves looked weird because the distribution would shift without the median changing, from memory?) @AurinaBMH do I remember right? Is this why we swapped to mean?
But whatever, whether mean or median, we should be consistent.

**Comment by AurinaBMH** [comment]
Yes, RC curves for rich/feeder/peripheral looked a little weird using median - jumping from value to value. 
From memory, now mean is used consistently, but we use ranksum test to compare distributions in all cases (except RC curves where we use ttest at each threshold), so this might be weird - using mean as a summary measure and using ranksum test when comparing distributions… sort of inconsistent. 

If we settle on using positive match measure as the main measure in the manuscript, the weirdness using the median might change. Also, we haven’t yet checked if the coexpression distributions are very non-normal using that measure. 

if we present lineage plot for all k (rich/feeder/peripheral curves) in supp, median there is not representative at all - no pint in showing it then.

**Comment by benfulcher** [comment]
Kind of yeah. The mean can be a useful visual summary of location.
But yes, we should probably either use median and ranksums throughout, or means and Welch's t-tests throughout (or switch based on some criteria for normality)
You're right -- let's wait for the newest results

**Comment by benfulcher** [comment]
Mean everywhere
