### ISSUE TITLE
Numbers

### ISSUE THREAD

**Issue by benfulcher** [AurinaBMH/WORMPlosCBtemplate#34]
@AurinaBMH Is there code to produce these numbers? Would help to have a small script. E.g., are gap junctions included in the "individual synapses" calculation -- if so it's misleading

> This network of 279 neurons consists of 2\,287 connected pairs of neurons, spanning a total of 2\,990 directed connections (and the weighted network includes a total of 8\,168 individual synapses).

**Comment by AurinaBMH** [comment]
If both electrical and chemical synapse exists, both are counted. 
gap junction matrix is also weighted, so I think it is right to sum both if there is an overlap. 

Maybe just use another word for that when all are included. 
counting ‘all synapses;
Adj = C.Adj_W{3}; 
Ns = sum(Adj(:)); 
Ns=8168

counting directed connections
Adj = C.Adj_B{3};
Ns = sum(Adj(:))
Ns = 2990

counting connected pairs
Adj = C.Adj_B{3};
Adj=triu(Adj|Adj'); 
Ns = sum(Adj(:))
Ns = 2287

**Comment by benfulcher** [comment]
Is this code somewhere? I can add it if not

**Comment by AurinaBMH** [comment]
it’s not saved in any script yet

**Comment by benfulcher** [comment]
Not sure how to phrase as weighted when gaps are in there; I might just remove the weighted result.
I guess future data may distinguish the direction of gap junctions but for now we represent as bidirectional

**Comment by benfulcher** [comment]
Ok I'll add a basic script for these stats

**Comment by benfulcher** [comment]
`BasicStats.m`
