### ISSUE TITLE
Avoid the "electrical"/"chemical" distinction

### ISSUE THREAD

**Issue by benfulcher** [AurinaBMH/WORMPlosCBtemplate#36]
This doesn't seem as precise (e.g., synaptic connections involve some component of electrical transmission) -- I think we should consistently say "synaptic" or "gap junction", and avoid saying "chemical" or "electrical" in the text.
E.g., fix Fig. 6A.

**Comment by benfulcher** [comment]
Also bits of text like:

> electrical, chemical reciprocal ($X \leftrightarrow Y$) and chemical unidirectional ($X \rightarrow Y$)

And Fig. S6

**Comment by AurinaBMH** [comment]
So the thing is an electrical synapse, while the gap itself is called gap junction (https://en.wikipedia.org/wiki/Electrical_synapse <https://en.wikipedia.org/wiki/Electrical_synapse>)

An electrical synapse is a mechanical and electrically conductive <https://en.wikipedia.org/wiki/Conductor_(material)> link between two neighboring neurons <https://en.wikipedia.org/wiki/Neuron> that is formed at a narrow gap between the pre- and postsynaptic neurons known as a gap junction <https://en.wikipedia.org/wiki/Gap_junction>. At gap junctions, such cells approach within about 3.5 nm of each other,[1] <https://en.wikipedia.org/wiki/Electrical_synapse#cite_note-Kandel00-1> a much shorter distance than the 20- to 40-nanometer distance that separates cells at chemical synapse <https://en.wikipedia.org/wiki/Chemical_synapse>.[2] <https://en.wikipedia.org/wiki/Electrical_synapse#cite_note-Hormuzdi04-2> In many animals <https://en.wikipedia.org/wiki/Animal>, electrical synapse-based systems co-exist with chemical synapses <https://en.wikipedia.org/wiki/Chemical_synapse>.

Are we still sticking with synaptic and gap distinction?

**Comment by AurinaBMH** [comment]
I think naming them electrical and chemical makes more sense because it reflects the nature of the connections. Synapse can be called a structure that transmits both chemical and electrical signals. 

**From wiki:** In the nervous system, a synapse is a structure that permits a neuron (or nerve cell) to pass an electrical or chemical signal to another neuron. 

**in Pan 2010** it's also names "... defined in terms of both electrical (gap junctional) and chemical (synaptic) connections between the neurons"

![image](https://user-images.githubusercontent.com/14971156/27811035-eb197538-60a4-11e7-9242-9a6c72b2f33d.png)

**Comment by benfulcher** [comment]
Ok -- looks like I'm wrong! Let's use electrical/chemical synapse terminology.
So I guess we should avoid saying simply "synapse" unless we mean all connections -- rather we should specify "electrical synapse" or "gap junction" versus "chemical synapse" when being specific?

**Comment by AurinaBMH** [comment]
Reading further Pan 2010, they use gap junctions and synaptic network terminology as well, so I don’t know who is right anymore :)

**Comment by benfulcher** [comment]
As long as we define our terminology and are consistent I think it's best. Let's go with synapse being either (even though it's typically associated with chemical; in which case probably just saying connection might be clearer), and try to specify throughout when we mean a specific one whether it's a chemical synapse or electrical/gap junction.
