### ISSUE TITLE
How is this computed??

### ISSUE THREAD

**Issue by benfulcher** [AurinaBMH/WORMPlosCBtemplate#38]
Unclear how you have an additive bar plot on a log_10 scale?? The y-axis is nonlinear...
![screen shot 2017-07-03 at 16 29 51](https://user-images.githubusercontent.com/4446070/27780544-dd8b6694-600c-11e7-857e-32e00b8d3654.png)

**Comment by benfulcher** [comment]
It seems like you need to either plot this upper plot as a scatter rather than bars, or have a separate subplot for each type if you want to use bars (so that the vertical axis will be correct)

**Comment by AurinaBMH** [comment]
It’s done with plot_neuronType.m script

I took a number of connections for each type (N) at each threshold and did log10(N). 
Than stacked those values on each other and plotted. 

Is that wrong?

**Comment by benfulcher** [comment]
Yeah, so then the stack will not have the right scale. E.g., if you have three types each have 100, then this will be 2+2+2 = 6 on the axis. But there are not 10^6 connections, there are 300.

**Comment by benfulcher** [comment]
Related question: are multifunctional neurons included in this? E.g., is it all sensory neurons or just neurons that are exclusively sensory

**Comment by AurinaBMH** [comment]
Yes, i see the problem. 
Scatter would look weird here, no?I’ll try. 

Sensory and others are not exclusively sensory (multimodal (overlapping) are included in each category).

**Comment by benfulcher** [comment]
Could even not show the upper plot. It's also confusing because the previous plot shows how many rich/feeder/peripheral. You kind of expect that this is the same sort of thing -- at each degree threshold how many rich links are sensory/motor/interneuron, but it's actually the total number of edges? Have a think about the least confusing way to show this. A line plot showing the number of connections of each type may work the best (e.g., on a log scale).
Wouldn't be the end of the world, though, if this upper plot was removed

**Comment by AurinaBMH** [comment]
![image](https://user-images.githubusercontent.com/14971156/27781147-06fc5c88-6010-11e7-9cfd-f8180e0e5a31.png)
This also looks weird... doesn't it?

**Comment by benfulcher** [comment]
Why weird? This is correct, right?
Ben

**Comment by AurinaBMH** [comment]
in general it’s correct, but plots are not aligned properly on x axis - looking into that now.

**Comment by AurinaBMH** [comment]
![image](https://user-images.githubusercontent.com/14971156/27781740-ae0cde92-6012-11e7-99c1-6ab0a32b86a4.png)

Matching now.

**Comment by benfulcher** [comment]
Ok — if you think this adds something useful, can keep it.
Seems like the old bar plots also didn’t match — now the upper and lower curves match,

**Comment by AurinaBMH** [comment]
Leaving this plot for now with lines.
