### ISSUE TITLE
RanksumVSttest. meanVSmedian

### ISSUE THREAD

**Issue by AurinaBMH** [AurinaBMH/WORMPlosCBtemplate#39]
If we do ranksum tests for Fig6, we should plot median as dashed line as well. 
Then we’d also need to use median for this plot to summarise coexpression at each threshold. 

if we do so, plotting means on other plots looks weird, no? But we decided to use means in all plots before. 
Eternal dilemma...

**Comment by benfulcher** [comment]
Median for coexpression

**Comment by AurinaBMH** [comment]
With median, now motor neurons also show increasing coexpression with degree. 
Science rules! 

![image](https://user-images.githubusercontent.com/14971156/27848325-a65f0bf4-6187-11e7-9bd2-c975f2c9f80f.png)

**Comment by benfulcher** [comment]
Ok! I wonder if you do a Wilcoxon rank sum test whether you can put circles over those that are significantly increased relative to other types of connections (or is this plot a bit weird in that you are only looking at the subnetwork involving connections to a given type of neuron so such a comparison is impossible...?)

**Comment by AurinaBMH** [comment]
hmmm…
these subnetworks are partially overlapping:
sensory is any+sensory
motor is any+motor
so ‘any’ in both cases can contain a portion of the same neurons…
Not sure if the comparison between groups here is straight forward. 

Also what about differences in k for different categories: only connections involving interneurons have degree higher than 42, what would we compare them to?

**Comment by benfulcher** [comment]
Yeah, I'm not suggesting comparing the three groups, but within each group you can do connections in that group versus all other connections in the network...?
This is like for the distance curve -- you compare the distance distribution in rich connections to that in all other types of connections.

**Comment by AurinaBMH** [comment]
Was just thinking about the null for neuron type (k) plot. 
do we want to compare coexpression in category X (e.g. interneuron) at the degree >k to:

1) maskNonspecial = ~mask & Adj; - all other links in the network including X category that are with degree <=k? (this way the matrix is split into 2 groups at each comparison)
OR
2) maskNonspecial = Adj&~maskDeg&~maskType; - links with degree <=k that don’t belong to X category, i.e. links where none of the members is e.g. interneuron? (some links are not considered in the comparison).

Results with both look similar, I would think the first null seems to be more reasonable, no?

**Comment by benfulcher** [comment]
I'm not fully on top of this, but I trust you. Go for 1)

**Comment by AurinaBMH** [comment]
Done with 1)
