### ISSUE TITLE
Robustness numerics for binary coexpression measures

### ISSUE THREAD

**Issue by benfulcher** [AurinaBMH/WORMPlosCBtemplate#4]
Address Fig. S1 concerns (listed as TODOs in caption), and update where this figure is mentioned in the main text.
Add the positive matching measure we develop, it's still important to include as motivation for our enrichment method (which is biased toward positive matches)

**Comment by AurinaBMH** [comment]
Will probably need to run the measure for positive matches fewer times than others (it takes ages to compute one matrix, so 1000 of them will take too long). 10 seems to be a low number, but the trend should be visible. What do you think?

**Comment by benfulcher** [comment]
How long does it take? Could it be done at a coarser resolution to speed up in this case? I think ~100 should be fine. Can run easily on massive. Do you need help on this one?

**Comment by AurinaBMH** [comment]
It’s around 2h for one run (the matrix which is correlated is 150x948 as in other cases) on massive desktop. 
I can make a script to submit slurm job, but it still will take ages…

Any thoughts how to speed up?

**Comment by benfulcher** [comment]
It's symmetric, right? Are you only computing the upper triangle? You could discretize the increments (e.g., rather than going from 5 through to 120 in increments of 1, you could go in increments of 2 for a big speedup, ~4 times). Should also use a parfor loop. On massive you can also distribute among hundreds of jobs to do it all in 2 h (each job does it with a different random number seed, then you combine them, rather than doing it serially). Want me to take a look? What's the code?

**Comment by AurinaBMH** [comment]
All the code is on massive M3 - the code is compareProportions.m (in /projects/kg98/aurina/CElegansGenes/Analysis/Genes)

Let me know if you have any troubles accessing it.
If you have a minute, would be good if you can have a look. I’m working on Michelle’s freesurfer today (jobs are finished). 

Just got a result from 10 runs (below). look sort of ok, no?
It’s running half a matrix and the adding the other half at the end.

**Comment by benfulcher** [comment]
You have to go into github to add images

**Comment by benfulcher** [comment]
Well, I've made some small changes, but it all looks ok to me. 10 is usually too few to average over, but if the trend is there maybe it's ok -- I mean we don't even use the measure directly

**Comment by AurinaBMH** [comment]
![pastedgraphic-1](https://cloud.githubusercontent.com/assets/14971156/25514683/f456719e-2c21-11e7-8a7f-1dd553eb5b9c.png)

**Comment by benfulcher** [comment]
Yeah that should be fine. It seems like there is bias only for tiny proportions, and then not so much? Its hard to see in too much detail... Have you run it on massive before? If you already have a slurm script set up, and if it's easy to just run it on massive over the weekend for 72 hours that could be good (which is 36 more iterations -- and change the for loop to a parfor loop and use 16 cores -- you might even get 36*16=576 iterations!)
But this is more for my curiosity than anything. I mean I suspect that you get very low values at low proportions because across all runs you never actually get a match (but when you do get a match it's very unlikely) so it's just a statistical effect of having a small sample -- to get good stats when there are very few ones is going to be harder... Still, the results surprise me because the theory of the measure doesn't seem like it should be biased in this way.
Anyway, if we don't actually use this measure directly in the paper, maybe it's ok to just put this in as-is -- it gives an idea...?

**Comment by AurinaBMH** [comment]
I'm running it a 100 times, will put an average of those into the supp hen it's done.
