### ISSUE TITLE
plot_neuronType.m

### ISSUE THREAD

**Issue by AurinaBMH** [AurinaBMH/WORMPlosCBtemplate#41]
Ben, can you have a look at this code?
Somehow, it gives Y axis weird values for the bottom plot - can't see the mistake. 

it's specified like: 
set(gca,'Ytick', [0 0.2 0.4 0.6 0.8 1], 'YTickLabel',[0 0.2 0.4 0.6 0.8 1], 'FontSize', 12);
in the script, but it gives 0, 10, 20...
![image](https://user-images.githubusercontent.com/14971156/27819925-bee305f2-60df-11e7-822e-ceab6cda3b09.png)

**Comment by benfulcher** [comment]
Not sure but I've updated the code now -- the defaults seem to work ok (values are ~low)??
![screen shot 2017-07-05 at 10 17 11](https://user-images.githubusercontent.com/4446070/27845790-7a4584e2-6175-11e7-928b-c89a2af4a16e.png)

**Comment by AurinaBMH** [comment]
Just pushed a version with new distributions added. 
Seemed like a lot of work to fit both plots to look nice in one figure, so for now it generates separate plot for curves and for distributions. 
Scales are ok as well.
