### ISSUE TITLE
Structure of confound section

### ISSUE THREAD

**Issue by benfulcher** [AurinaBMH/WORMPlosCBtemplate#42]
I thought we decided to put the control interneuron story as a possible confound in terms of function groups of neuron and list it at the end of the section?
Would be a section that says that many functional groups of neurons in C. elegans are known, so we investigated whether any of them might drive our results. We found that this particular system overlapped significantly with hubs (as previously characterized) and indeed has high coexpression.
Then some resolution saying that because hubs in C. elegans mostly contain neurons from this functional group, we are unable to distinguish the rich club effect from the similarity in gene expression between members of this functional group.
Because it is a different type of confound (not a confound to do with interneuron as a class of neurons), I think it belongs in a distinct section, as we discussed yesterday (was probably unclear because we changed the plan several times), but this is what I thought we landed on

**Comment by AurinaBMH** [comment]
Oh, ok. 
I somehow thought that we ended up deciding to combine this story with interneurons, therefore changed the plot for interneurons by adding two other distributions. 
I liked this bit at the end more, so happy to make another paragraph as a functional confound and leave interneuron story as i was before. 
Do we want to show a separate distribution plot for command hubs vs non-command hubs? Or just mention in the text with some p values?

**Comment by benfulcher** [comment]
I think adding a plot to the general one is important but don't put too much effort as what is in the plot is still up for grabs a bit. Work on the text and we can put the plot into that big one

**Comment by AurinaBMH** [comment]
general - you mean plot for extras? or for interneurons?

**Comment by benfulcher** [comment]
yeah extras

**Comment by AurinaBMH** [comment]
made a separate paragraph on command interneurons
