### ISSUE TITLE
Main schematic figure

### ISSUE THREAD

**Issue by benfulcher** [AurinaBMH/WORMPlosCBtemplate#43]
What do you think we should have?
I could adapt the `PlotModuleMatrix` code to just plot for a custom ordering, so you get the different types of rectangular annotations, and then remove the coexpression matrix...?
Did you have ideas for this? I think this is the only main thing remaining...

**Comment by AurinaBMH** [comment]
I think this would be more useful than coexpression matrix.
Could have 3 or 4 bars of information ordered head-tail with clear annotations instead.

**Comment by benfulcher** [comment]
In latest version of `plot_schematic`

**Comment by AurinaBMH** [comment]
I like the new schematic better. We probably need to have legends for bars to label main  neurotransmitters (red, yellow, blue), neuron types?
Also, neurotransmitter label angle is different from others.

**Comment by benfulcher** [comment]
Yeah all very rough and might add birth times but gives the idea for now

**Comment by AurinaBMH** [comment]
Yes, adding birth time should be informative!
