### ISSUE TITLE
Thresholding corrected p-values

### ISSUE THREAD

**Issue by benfulcher** [AurinaBMH/WORMPlosCBtemplate#51]
We need some justification for thresholding corrected p-values at 10^-4... Why do FDR correction if the corrected values are then thresholded arbitrarily...

**Comment by AurinaBMH** [comment]
Hmmm, 0.05 is also quite arbitrary…

Could do Benferroni correction and threshold at 0.05 (see what happens)
or
don’t do the correction and threshold with a stringent threshold. 

Alternatively could probably justify with the number of genes selected from the overall sample (either with percentage out of all genes in consideration or the absolute number)?
With p=0.0001
RF - 30/168 genes are selected =>17%
Connected 85/414 genes are selected =>20%

If we select p=0.05, then the number for connected doubles 164/414 =>40%, but the number for RF almost doesn’t change 35/168 =>20%. 
Therefore to keep the proportion of selected genes equal among the comparisons we choose a more stringent threshold. 

Let me know what you think :)

**Comment by benfulcher** [comment]
Well -- there is no point correcting if you then set a new arbitrary threshold on the corrected values. 0.05 is the standard (arbitrary) value used in neuroscience -- you can't just pick a different value every time you do a study.
I think you either say you kept the top 20% of genes for ORA, or you set the 0.05 threshold on corrected. I prefer the latter (the fact that you get lots of genes isn't automatically an argument that it must be rubbish).
But let's see how this section holds together; may work better around the individual gene story...
