### ISSUE TITLE
Number of pairs

### ISSUE THREAD

**Issue by benfulcher** [AurinaBMH/WORMPlosCBtemplate#52]
Lineage distance in Fig. 8C says 66 rich, 2173 non-rich; whereas for Fig. 8D it says 66 rich but 1490 non-rich. Is this inconsistent?

**Comment by AurinaBMH** [comment]
> 8C: 66 rich, 2173 non-rich in on neurons (all connections)
> 
> 8D: 66 rich but 1490 non-rich between early born neurons. 
Therefore, the number of non-rich is different while the number of rich is the same: all hubs are born early.
