### ISSUE TITLE
Authorship

### ISSUE THREAD

**Issue by AurinaBMH** [AurinaBMH/WORMPlosCBtemplate#53]
Decine if Taqi is on the paper. 
Alex suggests not to keep him, I would vote to keep him (6 weeks spent on something, I think is worth the 4th place, made some data arrangement easier for me).

**Comment by benfulcher** [comment]
I think Taqi should be on the paper--his contribution to the final version is minimal, but the groundwork was all his. I wonder if you can teach Alex to use github so he can weigh in on these conversations...

**Comment by benfulcher** [comment]
Can you get Alex's github and invite him to this repo? Perhaps he doesn't yet have a github account -- I've sent him an email trying to tempt him.

**Comment by AurinaBMH** [comment]
Sure, I’m happy to introduce him to our forum on issues :)

**Comment by alexfornito** [comment]
ok if you think so. Ben - I thought you tried to email him about this a while ago and he didn't respond?
Or am I confusing with someone else?

**Comment by benfulcher** [comment]
He's about the building at the moment -- working on something else. I mean he's not been very responsive and has been quite awkward when I've tried to talk to him, and said that he didn't think he did enough to justify being on the paper! But in my mind he did alot of the groundwork and coding. Yes it was simple, but it got the project off the ground... The question for me is where Roger wants to go as we want to recognize how important his input is...

**Comment by alexfornito** [comment]
suggest leaving author list off for now. lets see how much Rodge puts in.
If Taqi is not engaged, then I would be inclined to leave him off. He did the work as part of a paid internship. But, you are closer to the analysis then me and if you think the contribution was essential the I'll go with your opinion. Just have a personal grip with people who disengage.

**Comment by benfulcher** [comment]
Yeah fair enough. I mean he said he thought he should be excluded and never responded emails and has been evasive when I've tried to talk to him. Can discuss later; I've commented out the author names for now

**Comment by AurinaBMH** [comment]
Decided on authorship
