### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by AurinaBMH** [AurinaBMH/WORMPlosCBtemplate#55]
**Alex's suggestion: A gene expression signature of hub connectivity in the C. elegans connectome.** 
I think the new title is too much for the hub expression finding that we have. With this data and confounds, we don't actually have a signature for hubs here...
Like the old one better.

**Comment by benfulcher** [comment]
I agree saying that we have a gene expression signature for hub connectivity is too strong; I've changed it back ;)

**Comment by alexfornito** [comment]
Yes, I made the change before seeing the command IN result, which is pretty clear cut. I agree that my edit is not appropriate. Would be good to incorporate something about all the various facets of neurons though; e.g., "Hub connectivity, neuronal diversity and gene expression in the C elegans connectome"

**Comment by benfulcher** [comment]
Sounds good @alexfornito, I’ve used your new suggestion for now
