### ISSUE TITLE
Defining numbers

### ISSUE THREAD

**Issue by AurinaBMH** [AurinaBMH/WORMPlosCBtemplate#56]
Was not clear for Alex what’s the difference between two numbers: This network of 279 neurons consists of 2\,287 connected pairs of neurons, spanning a total of 2\,990 directed connections.

Better: This network of 279 neurons consists of 2\,287 connected neuron pairs (when both reciprocal and unidirectional connections counted equally), spanning a total of 2\,990 directed connections? Not really...

**Comment by benfulcher** [comment]
I think the original text is clearer

**Comment by alexfornito** [comment]
ok well its still unclear, so what is it that you are trying to say? IS it that the number 2990 is higher because it contains reciprocal connections?

**Comment by AurinaBMH** [comment]
2990 - the number of links (each link is counted once, therefore if a connection is reciprocal it is counted twice). 
2287 - the number of connected neuron pairs (reciprocal or unidirectional counted equally).

**Comment by alexfornito** [comment]
Yeah so maybe something like ³There are 2990 connections linking 2287 pairs of neurons, XX of which are unidirectional and XX which are reciprocal².
