### ISSUE TITLE
Name for coexpression coefficient

### ISSUE THREAD

**Issue by AurinaBMH** [AurinaBMH/WORMPlosCBtemplate#57]
Alex: still dont like r_phi - too confuding with RC. why not r', or just r?
We can acknolwdgee that it is sometimes called the phi coefficient but we denote with r to avoid confusion with RC. 

I like r_phi. 
Should we invent some new letter?

**Comment by benfulcher** [comment]
r is always Pearson correlation. r_\phi makes sense to me -- we can't use \phi because of overlap with RC coeff so we use r_\phi to distinguish it.

**Comment by alexfornito** [comment]
Using phi in both implicitly suggests they are related, which they are not. 

I really don't see the problem in saying something like: "This correlation coefficient is sometimes referred to as the phi coefficient (refs), but we denote it here as r' to avoid confusion with the rich-club coefficient, denoted as phi, and the Person correlation corefficient, which is conventionally denoted as r".

Alternatively, you could explicitly say after you define RC that phi should not be confused with r_phi and that the two are separate, but this still requires readers to keep this in mind and can make for a harder read.
