### ISSUE TITLE
Fig.1 

### ISSUE THREAD

**Issue by AurinaBMH** [AurinaBMH/WORMPlosCBtemplate#59]
- Alex wants a picture of worm on a side. AA:  would look weird as we now present a column with head/body/tail and the worm picture is not scaled.
- Change label sizes on all plots. 
- Add explanation for colors on bar plots. 
- Consider different color for a background (C). AA: then need to change connectivity background as well, but black looks good on that one.

**Comment by benfulcher** [comment]
Nothing major here -- can think about all these tiny tweaks when everything else is done

**Comment by AurinaBMH** [comment]
Need to fix this figure before sending to Alex

**Comment by benfulcher** [comment]
I've updated now

**Comment by AurinaBMH** [comment]
Labels on Fig 1 are a bit hard to read. 
Maybe do two rows for neurotransmitters and bigger on sensory, motor …?
Also bigger labels on axes for matrices?
maybe ‘synaptic connectivity’ for A should be changed to ‘connectivity’ or ‘neuronal connectivity’?

**Comment by benfulcher** [comment]
Ok fixed, @AurinaBMH better now?

**Comment by benfulcher** [comment]
Fixed
