### ISSUE TITLE
Modularity: main text

### ISSUE THREAD

**Issue by AurinaBMH** [AurinaBMH/WORMPlosCBtemplate#66]
Alex moved basic explanation about modules into methods and suggests to delete the first paragraph in the main text. 
AA: looks weird to me like that - like better the old version with only methods in methods part and explanation in the main text. 

Edited according to Alex now (old text commented in the main text).

**Comment by AurinaBMH** [comment]
Methods are the latest part in PLoS CB, so I kept background for both modules and lineage in results (and not in methods).

**Comment by benfulcher** [comment]
Ok -- the old version is commented out currently, though?

> %The \emph{C. elegans} connectome has a modular organization, and can be decomposed into groups of neurons or modules with dense inter-module connectivity (with relatively sparse connectivity between modules) \cite{Kim2014, Pan:2010jt, Bassett2010}, or into groups of neurons with more similar patterns of connectivity within groups than between groups \cite{Achacoso:1992ay, Pavlovic2014}.
> % , which can correspond to specific functional circuits
> %Given that connectome modules may correspond to functionally specialized systems, it is therefore plausible that neurons belonging to the same module might exhibit similar gene expression patterns, as has been shown for macroscopic functional networks in the human brain \cite{Richiardi2015}.
> %Brain network hubs generally participate in multiple modules \cite{vandenHeuvel:2013ij, deReus:2014cz}, and their dense rich-club connectivity implies that they may form their own module that overlaps with other, more specialized systems \cite{Fornito:2015dq, deReus:2013cy, ZamoraLopez:2010hy}.
> %We therefore investigated whether therefore increased gene coexpression between pairs of hub neurons in the \emph{C. elegans} connectome can be explained by their distribution across connectome modules.

**Comment by benfulcher** [comment]
@AurinaBMH Is this text somewhere new?

**Comment by AurinaBMH** [comment]
Replaced it with what Alex suggested. 
Could keep the old version if you like it better.

**Comment by AurinaBMH** [comment]
finalised
