### ISSUE TITLE
Birth time: additional figure

### ISSUE THREAD

**Issue by AurinaBMH** [AurinaBMH/WORMPlosCBtemplate#68]
Alex: As a broad group, connected pairs of early-born neurons do not exhibit significantly different gene coexpression compared to connected pairs of late-born neurons (Wilcoxon rank sum test, $p = 0.64$), but connected pairs of early-born neurons do exhibit significantly higher gene coexpression relative to pairs of connected neurons for which one neuron is born prior to hatching and the other is born post-hatching (Wilcoxon rank sum test, $p = 4.2 \times 10^{-3}$).
Should have a figure (maybe in supp)

AA: maybe in supp, not in the main text - already too many distributions in the main text.

**Comment by benfulcher** [comment]
Perhaps we can assemble a list of all distributions that Alex wants us to show, and just dump them all in a massive supp if this is required. I'm happy to just display the important ones and quote results in text for minor points.

**Comment by alexfornito** [comment]
Its unclear why you would prioritise displaying some results over others. why should birth times be in supps but not modules? I think Fig 8 can be multi-panel and include distributions for all relevant 'potential driver' analyses.
