### ISSUE TITLE
Compare our hubs to Towlson

### ISSUE THREAD

**Issue by benfulcher** [AurinaBMH/WORMPlosCBtemplate#7]
Needs to be crystal clear differences between us and Towlson, through that hub connectivity section of results:

- [x] How similar are our hubs to Towlson's list of hubs? Explain why (different connectome, non-symmetrized, not including gapjs)
- [x] How similar is our RC curve?

**Comment by AurinaBMH** [comment]
Details here: https://www.evernote.com/shard/s94/nl/2147483647/2a302310-df5d-4350-878e-dabe7373993b/

Will add to the text.

**Comment by AurinaBMH** [comment]
Comparison is made in the text. 
Don't think we should compare the form of RC curve in detail in the text: basically similar neurons as in towlson, degrees are different. Noted that different variation of the connectome is used.
