### ISSUE TITLE
Neurotransmitters

### ISSUE THREAD

**Issue by AurinaBMH** [AurinaBMH/WORMPlosCBtemplate#70]
Alex: provide details of permutation test in supps. The description here a little unclear and no need to have this detail here.

Will need to make a supp paragraph about permutation testing then. 
This part commented in the main text now.

**Comment by AurinaBMH** [comment]
Alex also wants a figure for permutation result
AA: don't think there is a figure to show for it. Distribution with a line for the empirical result will look very weird...

**Comment by AurinaBMH** [comment]
Combine details about permutation testing in both anatomy and neurotransmitters into one paragraph for supp. All details commented out now in the main text.

**Comment by benfulcher** [comment]
I disagree, I think it's clear.

**Comment by alexfornito** [comment]
Ok maybe not necessary in supps, but wording should be clarified:

"we used a permutation test to 534
compute the mean coexpression between all pairs of random groups of sixteen neurons 535
of the same neurotransmitter types (e.g., thirteen random cholinergic neurons, two 536
random glutamatergic neurons, and one random neuron of unknown neurotransmitter 537
type) across 1  106 permutations."

The permutation test does not compute the mean coexpression. 
Did you really look at ALL possible pairs?
What statistical test exactly was performed? Did you just get sets of 16 random genes (constrained by neurochem), compute the mean coexpression and see whether the observed hub coexpression sits in this distribution? If so, this could be stated more clearly

**Comment by benfulcher** [comment]
> The permutation test does not compute the mean coexpression.

Good point -- clarified.

> Did you really look at ALL possible pairs?

Oh whoops, I mean the mean computed between all pairs of each random set of 16.

> What statistical test exactly was performed? Did you just get sets of 16 random genes (constrained by neurochem), compute the mean coexpression and see whether the observed hub coexpression sits in this distribution? If so, this could be stated more clearly

Yes; this is all we did (except actually using median). I've updated in the text; hopefully clear now!
