### ISSUE TITLE
Anatomical location

### ISSUE THREAD

**Issue by AurinaBMH** [AurinaBMH/WORMPlosCBtemplate#71]
Alex wants a figure for this: 
Within the head, gene coexpression 555
is significantly increased amongst hub neurons relatively to other pairs of head neurons
(Wilcoxon rank sum test, ... for 46 hub-hub pairs and 1 186 others), and 
also amongst head/tail pairs of neurons (Wilcoxon rank sum test, ...  for 23
hub-hub pairs, 174 others), but not for the three hub neurons in the tail (Wilcoxon rank 
sum test, p = 0:15 for three hub-hub pairs, 53 others)

AA: don't think we need more plots. - they would again show distributions...

**Comment by benfulcher** [comment]
Yeah I think it's fine to just quote the results of these tests

**Comment by alexfornito** [comment]
ok
