### ISSUE TITLE
Functional class

### ISSUE THREAD

**Issue by AurinaBMH** [AurinaBMH/WORMPlosCBtemplate#72]
Alex wants: Better to comment on comparison of non-command hub INs vs non-hub INs, as per my comment on fig 8.

AA: non-command hubs don't have higher coexpression than other interneurons, so comparison would not make the point clear. same with showing an additional distribution. 
Need to decide if we include an additional distribution then.

**Comment by benfulcher** [comment]
If non-command hub INs have weaker coexpression than non-hub INs, then this is important to say (if not show) -- gives even more weight to the idea that this is a control IN effect.

**Comment by alexfornito** [comment]
I agree. We should show this effect.

**Comment by alexfornito** [comment]
otherwise it feels a little like cherry-picking.
