### ISSUE TITLE
Enrichment

### ISSUE THREAD

**Issue by AurinaBMH** [AurinaBMH/WORMPlosCBtemplate#73]
Alex: far too much text devoted to non-significant findings. Should just say in a few lines nothing survived FDR, but these were top-ranked categories.... result may be due to incomplete gene expression data... tables in supps.

AA: need to decide if we still list GO categories and also include list of genes in the supp (probably top 20-25 as table) and others as supp data in a separate file. Or do something else.

**Comment by benfulcher** [comment]
Once all of these results are up, we should sit down and discuss how we're going to present the enrichment. I think probably focusing in on some key genes that came up near the top and interpreting them in the context of what's known will be most interesting (will need Roger's help for this).
Then if the main story is around individual genes, each with their own corrected p-values, can mention that enrichment is problematic on these data, but highlighted some interesting categories (such as glutamate) but did not reach significance; future work with more complete data may be able to use the methods developed here to make more detailed conclusions using enrichment analysis.

**Comment by alexfornito** [comment]
For now I suggest generating a table with the individual hits and a separate one for the Go categories. In the draft we can then flag to Roger that we would like his opinion. He can guide us as to which genes we should think more about.
