### ISSUE TITLE
Chemical and electrical enrichment

### ISSUE THREAD

**Issue by AurinaBMH** [AurinaBMH/WORMPlosCBtemplate#76]
Chemical: no genes have even remotely lower scores. all >0.04 (2). 
Electrical: Top genes are all about transmitters - some Ach, one GABA (and they are not supposed to be). Nothing directly related to electrical transmission. 
![image](https://user-images.githubusercontent.com/14971156/28301564-f45ac512-6bca-11e7-8669-ecf61be8297a.png)

**Comment by benfulcher** [comment]
Hmmm... So we're getting chemical genes when we look for increases in electrical. Are you sure the coding scores genes in the right direction? If so, this may be a hard sell... Kind of undermines the method entirely :/

**Comment by AurinaBMH** [comment]
genes for ch/el not included in the manuscript
