### ISSUE TITLE
Distance effect

### ISSUE THREAD

**Issue by benfulcher** [AurinaBMH/WORMPlosCBtemplate#77]
Median distance doesn't really increase -- because it's bimodal the median is in the head and doesn't capture the increase in the tail. So better to show mean which captures this increased density in head-tail connections (which median is not sensitive to).
But there is no longer significant difference under ranksum test (where there used to be under t-test)... I guess we do want to look for differences in the mean since the head-tail connections are extreme but are real; i.e., not 'outliers'...

<img width="502" alt="screen shot 2017-07-20 at 11 44 44" src="https://user-images.githubusercontent.com/4446070/28399673-216f0b7c-6d41-11e7-97f5-9760b0e03a99.png">

**Comment by benfulcher** [comment]
Non-Gaussian, but we're interested in differences in the mean. It kind of goes against the hypotheses of the test, but I think we leave this as a t-test...???

**Comment by AurinaBMH** [comment]
ttest is fine with me
