### ISSUE TITLE
Gap junction as weighted?

### ISSUE THREAD

**Issue by benfulcher** [AurinaBMH/WORMPlosCBtemplate#78]
`while the gap junction network is conventionally represented as an weighted undirected network`
@AurinaBMH is this true? I thought gap junction network was unweighted? How do they derive weights?

**Comment by AurinaBMH** [comment]
Yes, gap junction network is weighted. Weighs - the number of gap junctions between neurons (gap junctions are channels, so it's possible to count them).

**Comment by benfulcher** [comment]
Oh cool — can you make sure this is clear in the text. I may have downplayed this.
