### ISSUE TITLE
"Gene coexpression" or "Correlated gene expression (CGE)"

### ISSUE THREAD

**Issue by benfulcher** [AurinaBMH/WORMPlosCBtemplate#80]
Maybe we should go ahead and use the term “correlated gene expression”…?
Coexpression has connotations of pairs of genes.
The same term ‘correlated gene expression' was used by Richiardi…
Worth thinking about in context of worm.
cf. also in mouse: Mills, B. D. et al. Correlated gene expression and anatomical communication support synchronized brain activity in the mouse functional connectome. bioRxiv 167304 (2017). [doi:10.1101/167304](http://biorxiv.org/lookup/doi/10.1101/167304)

**Comment by AurinaBMH** [comment]
That’s a good point - and we could use the short version in the text.

**Comment by benfulcher** [comment]
I've tried to use correlated gene expression (CGE) now, and avoided "coexpression" throughout -- see how it flows
