### ISSUE TITLE
Gap junctions -> distance relationships

### ISSUE THREAD

**Issue by benfulcher** [AurinaBMH/WORMPlosCBtemplate#81]
Investigate distribution of inter-neuron distances for electrical gap junctions.
Does this constrain the spatial relationships?
Could plot electrical synapses differently in the spatial plot

**Comment by benfulcher** [comment]
@AurinaBMH We don't say anything about this, but you did some analysis, right? We should check with Roger why electrical gap junctions can be long-distance; perhaps add a sentence somewhere to interpret what electrical synapses actually represent, (e.g., in spatial section), mentioning the distance distribution of chemical/electrical. I remember you ran this analysis; can you remind me the result? Ta 👍

**Comment by AurinaBMH** [comment]
There is no significant difference in distance between chemical and electrical synapses (red - chemical, green - electrical). 
p = 0.6334. 
I don’t really see why electrical should be closer than chemical - both synapses can connect end of the axon with cell body (see http://www.nature.com/nrn/journal/v6/n3/fig_tab/nrn1627_F4.html <http://www.nature.com/nrn/journal/v6/n3/fig_tab/nrn1627_F4.html> - example in mouse retina) :)

**Comment by AurinaBMH** [comment]
![image](https://user-images.githubusercontent.com/14971156/30841285-07923a4a-a2bf-11e7-93ba-916448051989.png)

**Comment by AurinaBMH** [comment]
added a line in 
\subsection*{Correlated gene expression and connectivity}
