### ISSUE TITLE
Cleaning up references

### ISSUE THREAD

**Issue by benfulcher** [AurinaBMH/WORMPlosCBtemplate#88]
@AurinaBMH make sure you clean up references.
For example, the bib style file is displaying all dois, which I don't think PLoS CB needs.
Make sure all journal names are consistent, and fields are all in place (and hopefully there are no duplicates!). I've just gone through my library.

**Comment by AurinaBMH** [comment]
Thanks for incorporating Roger’s feedback :)
I will go through my library today.
