### ISSUE TITLE
Over-selling Vertes human results

### ISSUE THREAD

**Issue by AurinaBMH** [AurinaBMH/WORMPlosCBtemplate#89]
Alex suggests to replace: 
Investigations of mesoscale network organization in the mouse have identified a distinctive transcriptional signature of neural hubs, characterized by tightly coupled expression of genes regulating oxidative metabolism, with similar genes characterizing macroscale inter-modular hub regions of the human cortex.

With: 
Recent work in the mouse and humans suggests that brain network hubs carry a distinctive transcriptional signature characterised by tightly coupled gene expression relative to other pairs of brain regions.

The second part about human is not true - they don't show coupled gene expression.

**Comment by benfulcher** [comment]
Discuss in #92
