### ISSUE TITLE
Framing context of mouse/human results

### ISSUE THREAD

**Issue by benfulcher** [AurinaBMH/WORMPlosCBtemplate#92]
> Recent work in the mouse and humans suggests that brain network hubs carry a distinctive transcriptional signature characterised by tightly coupled gene expression relative to other pairs of brain regions.

An issue with this narrative is that the human results do not show evidence for correlated gene expression because no pairwise analysis was done. Human results support the ATP/metabolic genes story (which we can't probe here), but not the coupled expression story. We need to be more nuanced on this point. Because we can't probe the metabolic hypothesis, I think it's better to leave it out of the abstract; sets the reader to think that we're able to test convergent results in human and mouse in worm, which we can't due to the data.

**Comment by alexfornito** [comment]
well, the PLS still identifies a component of covariance between participation coefficient and metabolic gene expression right? Help for you to reword to acknowledge nuance

**Comment by benfulcher** [comment]
But this doesn't give us information about correlated gene expression... We could add a sentence or two explaining the human results in more detail in discussion?
Clearer story would be to just mention the mouse in abstract/grandstanding...? We can't actually test any predictions made in human. I mean the human study implies something transcriptionally unique about hubs, and this would drive an increase in CGE (everything else equal), but it wasn't tested if everything else was equal, so there is no evidence about whether CGE is increased in pairs of hubs in humans...
@alexfornito are you ok with dropping the human work from the main narrative (e.g., in abstract)? Or we could try adding a weaker statement; since the human work hints at the fact that hubs *may* also be transcriptionally similar...

**Comment by alexfornito** [comment]
Sure drop from abstract. Elsewhere, focus on mouse and say that human provides supporting evidence
