### ISSUE TITLE
Making code and data available

### ISSUE THREAD

**Issue by benfulcher** [AurinaBMH/WORMPlosCBtemplate#93]
> Should we provide a matlab workspace that contains all these data? We should indicate link here.
All code will be provided too?

We should provide a github link to our repository (private until manuscript is accepted?), that includes links to raw data files and scripts for processing the data. If data files are too big, can host on Monash figshare.

**Comment by alexfornito** [comment]
yep good. I also want to create a 'resources' link on the lab webpage. we should chat about how to integrate with git.

i fell so hi-tech using this forum :)

**Comment by benfulcher** [comment]
The resources page can just link to the lab github...?
When manuscript is ready, @AurinaBMH and I can meet to put a clean version on github/figshare.
Often code/data are kept private until acceptance; we can discuss whether we make the code open with the preprint or wait until after review...

**Comment by alexfornito** [comment]
Much of this comes from my git naiveté so perhaps you can run me through next meeting

**Comment by benfulcher** [comment]
Happy to 😁

**Comment by benfulcher** [comment]
@AurinaBMH has worked this up and Stuart tested. Hi five for reproducible science 👍🏻
