### ISSUE TITLE
Using Pearson

### ISSUE THREAD

**Issue by benfulcher** [AurinaBMH/WORMPlosCBtemplate#94]
Throughout we're using the mean squared contingency coefficient; my (related) metric can be interpreted like a _p_-value, whereas the $r_\phi$ is more interpretable, analogous to the linear Pearson correlation coefficient.
AF: we agreed on this previously, but let us know if you think this doesn't work. Otherwise you can comment and close this issue.

**Comment by alexfornito** [comment]
ok this is fine. was more for my understanding. My memory is that we chopped and changed a few times and I thought the final call was to stick with your method throughout. to a certain extent that option is more elegant, but i think current format is fine
