### ISSUE TITLE
'Origin' and 'termination'

### ISSUE THREAD

**Issue by benfulcher** [AurinaBMH/WORMPlosCBtemplate#95]
> Specifically, we selected a subset of nonhub interneurons that most closely resemble the anatomical properties of hub interneurons, in terms of their origin and termination locations (AVFL, AVFR, AVHL, AVHR, AVKR, AVJL, AVJR).

AF finds it unclear to say 'origin' and 'termination'. Roger seemed to find it clear. Is by 'origin' the nucleus? And termination is the full extent of the neuron? I agree it's not super clear; AA: if you're not too sure, can shoot Roger a quick email to clarify...?

**Comment by AurinaBMH** [comment]
I will email Roger and ask what's a better way to describe it.

**Comment by AurinaBMH** [comment]
RP: You could use ‘position' and 'projection pattern’ instead of origin and termination.
