### ISSUE TITLE
Keep conclusion?

### ISSUE THREAD

**Issue by benfulcher** [AurinaBMH/WORMPlosCBtemplate#96]
Conclusion is not required by PLoS CB. Agree with Alex that we can remove.
Let me know if you agree -> can close this issue

**Comment by AurinaBMH** [comment]
In the PlosCB template, there is the conclusions section. Probably should keep, no?

**Comment by benfulcher** [comment]
It's optional; e.g., Miner, D. & Triesch, J. Plasticity-Driven Self-Organization under Topological Constraints Accounts for Non-random Features of Cortical Synaptic Wiring. PLoS Comp. Biol. 12, e1004759–21 (2016).
[Link](http://dx.plos.org/10.1371/journal.pcbi.1004759)

**Comment by AurinaBMH** [comment]
ok, then we don't need it.
